#  ____  _                           _____
# |  _ \(_)                         / ____
# | |_) |_ _ __   __ _ _ __ _   _  | (___   ___ _ __  ___  ___  _ __
# |  _ <| | '_ \ / _` | '__| | | |  \___ \ / _ \ '_ \/ __|/ _ \| '__|
# | |_) | | | | | (_| | |  | |_| |  ____) |  __/ | | \__ \ (_) | |
# |____/|_|_| |_|\__,_|_|   \__, | |_____/ \___|_| |_|___/\___/|_|
#                           |___/
# Les capteurs binaires permettent de représenter l'état d'un appareil qui peut
# retourner une valeure booléene (0 ou 1)
#
# https://www.home-assistant.io/components/binary_sensor/
#
binary_sensor: !include_dir_list ../Includes/binary_sensors
