#   ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗ ██╗   ██╗██████╗  █████╗ ████████╗██╗ ██████╗ ███╗   ██╗
#  ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝ ██║   ██║██╔══██╗██╔══██╗╚══██╔══╝██║██╔═══██╗████╗  ██║
#  ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗██║   ██║██████╔╝███████║   ██║   ██║██║   ██║██╔██╗ ██║
#  ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║██║   ██║██╔══██╗██╔══██║   ██║   ██║██║   ██║██║╚██╗██║
#  ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝╚██████╔╝██║  ██║██║  ██║   ██║   ██║╚██████╔╝██║ ╚████║
#   ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ╚═╝ ╚═════╝ ╚═╝  ╚═══╝



homeassistant:

  name: Maison
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Paris
#  external_url: !secret external_url
  internal_url: !secret internal_url
  media_dirs:
    media: /media


  allowlist_external_dirs: 
    - /media
    - /config/


  
  # Load packages
  packages: !include_dir_named integrations



#  _______        _     _                    _____  _____ _____ _____
# |__   __|      | |   | |            /\    / ____|/ ____|_   _|_   _|
#    | | _____  _| |_  | |_ ___      /  \  | (___ | |      | |   | |
#    | |/ _ \ \/ / __| | __/ _ \    / /\ \  \___ \| |      | |   | |
#    | |  __/>  <| |_  | || (_) |  / ____ \ ____) | |____ _| |_ _| |_
#    |_|\___/_/\_\\__|  \__\___/  /_/    \_\_____/ \_____|_____|_____|
#
#   http://patorjk.com/software/taag/#p=display&f=Big&t=Home-Assistant







